# Generated by Django 5.1.3 on 2024-12-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('jurnalist', 'jurnalist'), ('hodim', 'hodim')], max_length=10),
        ),
    ]
