"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d@(vl_xd3ee&ny)wpcg+d-cbj1@2c$#%28)el@@baoa&ousv+8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app',"*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'accounts',
    'whitenoise.runserver_nostatic',
    'post',
    'parler',
    'embed_video'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.RecordVisitorMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('uz', 'O‘zbekcha'),
    ('en', 'English'),
    ('ru', 'Русский'),
]

PARLER_LANGUAGES = {
    None: (
        {'code': 'en'},
        {'code': 'ru'},
        {'code': 'uz'},
    ),
    'default': {
        'fallback': 'en',
        'hide_untranslated': False,
    }
}

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Tarjima fayllari uchun papka
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files
# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

AUTH_USER_MODEL = 'accounts.User'


JAZZMIN_SETTINGS = {
    "site_title": "Admin panel",  # Panelning sarlavhasi
    "site_header": "TalTes",  # Panelning yuqori sarlavhasi
    "site_brand": "",  # Brend logotipi yonidagi matn
    "site_logo": "/static/img/icon1.png",  # Logotip (STATIC papkadagi faylga yo'l)
    "site_logo_classes": "",  # Logotip uchun CSS sinflari
    "welcome_sign": "Xush kelibsiz, admin!",  # Kirish paytida ko'rsatiladigan xabar
    "copyright": "© 2024 TalTes",  # Pastki qismdagi matn
    "search_model": "auth.User",  # Qidirish uchun model

    # Menyu sozlamalari
    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},  # Foydalanuvchilar modeli uchun havola
    ],
    "usermenu_links": [
        {"name": "Profilim", "url": "/profile/", "new_window": False},
    ],

    # Yon menyu
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": ["auth"],  # Ko'rinmas app-lar
    "hide_models": ["auth.Group"],  # Ko'rinmas modellar

    # Ranglar va stillar
    "theme": "cerulean",  # Bootstrap mavzusi (cerulean, darkly, lux, va h.k.)
    "dark_mode_theme": "solar",  # Qorong'i rejim mavzusi

    # Piktogramma sozlamalari
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    # Model sozlamalari
    "default_icon_parents": "fas fa-chevron-circle-right",  # Yon menyu ota elementlari
    "default_icon_children": "fas fa-circle",  # Yon menyu ichki elementlari

    # Xabarlar
    "welcome_sign": "Panelga xush kelibsiz!",

    # Logotip va brend uchun foydalanuvchi rasmlari
    "user_avatar": "profile.image",  # Foydalanuvchi profil rasmi
}

# Jazzmin UI tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark navbar-primary",  # Bosh menyu ranglari
    "sidebar": "sidebar-dark-primary",  # Yon menyu ranglari

}
